### ISSUE TITLE
Does not work in zsh

### ISSUE THREAD

**Issue by maxdanilov** [antoniomo/gcloud-ps1#1]
Usage:
```
source ~/gcloud-ps1/gcloud-ps1.sh
PROMPT=$PROMPT'$(gcloud_ps1)$ '
```

Output:
```
gcloud_ps1:11: character not in range
```

prompt looks like:
```
~  (\[\]$'$
```

**Comment by antoniomo** [comment]
Hi! I don't use zsh, but I'll try to take a look over the weekend :)

**Comment by antoniomo** [comment]
Hi,

I couldn't reproduce the issue, does your terminal/font support unicode? Could you try with no icon?

https://github.com/antoniomo/gcloud-ps1#no-iconcustomize-the-icon

**Comment by maxdanilov** [comment]
Hi @antoniomo , thanks for your investigation.

This kind of helped, now the prompt looks like this:
```
(\[\]<my project name>\[\])$
```
Still, for some reason I see those escape chars (`(\[\]`, `\[\])`)

If that helps, I'm using MacOS 10.15.1, zsh 5.7.1 
I'm pretty sure Unicode chars usually work for me.

**Comment by antoniomo** [comment]
From the looks of it, it might be how tput/colors work on Mac (iterm2?). I'll try to get a friend with a mac to test (I only have Linux available at the moment). Unfortunately that will take a few days, but I'll write back once it's sorted out.

**Comment by maxdanilov** [comment]
No problem, thank you for your efforts :)
I'm using iTerm2 indeed, v. 3.3.6

**Comment by antoniomo** [comment]
Hi! I think this is fixed, sorry for the delay!

Let me know if the fix doesn't work, I couldn't test your exact version but I hope it doesn't matter :)

**Comment by maxdanilov** [comment]
Awesome, works well 🎉 
Thanks for your fix 🙇

**Comment by antoniomo** [comment]
Anytime! Happy that you find it useful :)
